#!/usr/bin/env bash
# A Bash script that displays running processes in a user-friendly format with full timestamp

ps -eo user,lstart,cmd --sort=start_time | awk '
BEGIN {
    print "USER STARTED CMD"
}
NR>1 {
    # Format the STARTED time as HH:MM:SS (columns 4,5,6)
    started_time = $4
    if (length(started_time) == 0) next
    printf "%s %s:%s:%s %s\n", $1, substr($5, 1, 2), substr($5, 4, 2), s
