#!/usr/bin/env bash
# This script runs indefinitely and prints a message when it receives SIGTERM

trap 'echo "I am invincible!!!"' SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
