#!/usr/bin/env bash
# This script runs indefinitely and handles SIGTERM by printing a custom message

# Trap SIGTERM and define custom behavior
trap 'echo "I am invincible!!!"' SIGTERM

# Infinite loop
while true
do
    echo "To infinity and beyond"
    sleep 2
done
